package net.dwarfguide.creature.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class AttributesBasedStrategy_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_mald5q_a(editorContext, node);
  }

  private EditorCell createCollection_mald5q_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_mald5q_a");
    editorCell.addEditorCell(this.createConstant_mald5q_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_mald5q_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_mald5q_b0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new RaceProfessionComponent(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createConstant_mald5q_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "attributes based strategy for");
    editorCell.setCellId("Constant_mald5q_a0");
    Dwarfs_StyleSheet.getKeyword(editorCell).apply(editorCell);
    editorCell.setDefaultText("");
    return editorCell;
  }
}
