package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class AttributesBasedStrategy_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements RatingStrategy_BehaviorDescriptor {
  public AttributesBasedStrategy_BehaviorDescriptor() {
  }

  public SNode virtual_race_6143566370761776415(SNode thisNode) {
    return HasRaceContraint_Behavior.virtual_race_6143566370761776415(thisNode);
  }

  public SNode virtual_profession_7730107903695144631(SNode thisNode) {
    return HasProfessionConstraint_Behavior.virtual_profession_7730107903695144631(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.AttributesBasedStrategy";
  }
}
