package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class AttributeRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public AttributeRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.AttributeRef";
  }
}
