package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public interface HasName_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
  public String virtual_getSanitizedName_3848777903716100296(SNode thisNode);
}
