package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface HasProfessionConstraint_BehaviorDescriptor {
  public SNode virtual_profession_7730107903695144631(SNode thisNode);
}
