package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class HasProfessionConstraint_Behavior {
  private static Class[] PARAMETERS_7730107903695144631 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_profession_7730107903695144631(SNode thisNode) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "professionRef", true), "profession", false);
  }

  public static SNode call_profession_7730107903695144631(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "net.dwarfguide.creature.structure.HasProfessionConstraint"), "virtual_profession_7730107903695144631", PARAMETERS_7730107903695144631);
  }

  public static SNode callSuper_profession_7730107903695144631(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "net.dwarfguide.creature.structure.HasProfessionConstraint"), callerConceptFqName, "virtual_profession_7730107903695144631", PARAMETERS_7730107903695144631);
  }
}
