package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface HasRaceContraint_BehaviorDescriptor {
  public SNode virtual_getRace_6143566370761776415(SNode thisNode);
}
