package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Profession_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Entity_BehaviorDescriptor {
  public Profession_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public String virtual_getSanitizedName_3848777903716100296(SNode thisNode) {
    return HasName_Behavior.virtual_getSanitizedName_3848777903716100296(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.Profession";
  }
}
