package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ProfessionRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ProfessionRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.ProfessionRef";
  }
}
