package net.dwarfguide.creature.behavior;

/*Generated by MPS */


public interface RatingStrategy_BehaviorDescriptor extends HasRaceContraint_BehaviorDescriptor, HasProfessionConstraint_BehaviorDescriptor {
}
