package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class SkillRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SkillRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.SkillRef";
  }
}
