package net.dwarfguide.creature.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Statistic_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Statistic_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "net.dwarfguide.creature.structure.Statistic";
  }
}
