package net.dwarfguide.creature.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("net.dwarfguide.creature", "ec18e679-bd6d-4441-a00b-ab06c2d44eec"), SModelReference.fromString("r:2ed640f1-ef9d-4ab2-87bd-9aa7ef6046fd(net.dwarfguide.creature.intentions)"));
  }

  public void init() {
    add(new GenerateId_Intention(), "2455624152132987133");
    add(new PopulateRaceWithFileds_Intention(), "2455624152132456396");
  }
}
