package net.dwarfguide.model.core;

/*Generated by MPS */


public abstract class AbstracRatingStrategy implements RatingStrategy {
  private String myDescription;
  private RaceEnum myRace;
  private ProfessionEnum myProfession;

  protected AbstracRatingStrategy(String description, RaceEnum raceEnum, ProfessionEnum professionEnum) {
    this.setDescription(description);
    this.setRace(raceEnum);
    this.setProfession(professionEnum);
  }

  public String getDescription() {
    return this.myDescription;
  }

  private void setDescription(String value) {
    this.myDescription = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public ProfessionEnum getProfession() {
    return this.myProfession;
  }

  private void setProfession(ProfessionEnum value) {
    this.myProfession = value;
  }
}
