package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.18", comments = "Generated from model net.dwarfguide.model.core")
public class Application {
  public Application() {
  }

  public String getGeneratedDate() {
    return Application.class.getAnnotation(Generated.class).date();
  }
}
