package net.dwarfguide.model.core;

/*Generated by MPS */

import java.util.Map;
import java.util.EnumMap;

public class Creature {
  private Map<AttributeEnum, Integer> attributes;
  private Map<SkillEnum, Integer> skills;
  private Map<TraitEnum, Integer> traits;
  private String myName;
  private String myNickname;
  private RaceEnum myRace;

  public Creature() {
    attributes = new EnumMap<AttributeEnum, Integer>(AttributeEnum.class);
    skills = new EnumMap<SkillEnum, Integer>(SkillEnum.class);
    traits = new EnumMap<TraitEnum, Integer>(TraitEnum.class);

    traits.put(TraitEnum.NERVOUSNESS, 50);
    traits.put(TraitEnum.RAGE, 50);
    traits.put(TraitEnum.DEPRESSION, 50);
    traits.put(TraitEnum.NEUROSIS, 50);
    traits.put(TraitEnum.URGE, 50);
    traits.put(TraitEnum.STRESS, 50);
    traits.put(TraitEnum.FRIENDLY, 50);
    traits.put(TraitEnum.COMPANY, 50);
    traits.put(TraitEnum.LEADERSHIP, 50);
    traits.put(TraitEnum.ACTIVENESS, 50);
    traits.put(TraitEnum.THRILLSEEKING, 50);
    traits.put(TraitEnum.OPTIMISM, 50);
    traits.put(TraitEnum.IMAGINATION, 50);
    traits.put(TraitEnum.ARTISTIC, 50);
    traits.put(TraitEnum.EMOTION, 50);
    traits.put(TraitEnum.ADVENTURE, 50);
    traits.put(TraitEnum.THINKING, 50);
    traits.put(TraitEnum.REBELLIOUSNESS, 50);
    traits.put(TraitEnum.TRUSTING, 50);
    traits.put(TraitEnum.HONESTY, 50);
    traits.put(TraitEnum.HELPFULNESS, 50);
    traits.put(TraitEnum.COMPROMISING, 50);
    traits.put(TraitEnum.MODESTY, 50);
    traits.put(TraitEnum.COMPASSION, 50);
    traits.put(TraitEnum.CONFIDENCE, 50);
    traits.put(TraitEnum.ORGANIZATION, 50);
    traits.put(TraitEnum.LAWFULNESS, 50);
    traits.put(TraitEnum.EXCELLENCE, 50);
    traits.put(TraitEnum.PERSEVERANCE, 50);
    traits.put(TraitEnum.CAUTIOUSNESS, 50);
  }

  public int getAttribute(AttributeEnum attributeEnum) {
    return attributes.get(attributeEnum);
  }

  /*package*/ void setAttribute(AttributeEnum attributeEnum, int value) {
    attributes.put(attributeEnum, value);
  }

  public int getSkill(SkillEnum skillEnum) {
    return skills.get(skillEnum);
  }

  /*package*/ void setSkill(SkillEnum skillEnum, int value) {
    skills.put(skillEnum, value);
  }

  public int getTrait(TraitEnum traitEnum) {
    return traits.get(traitEnum);
  }

  /*package*/ void setTrait(TraitEnum traitEnum, int value) {
    traits.put(traitEnum, value);
  }

  public String toString() {
    return "{" + this.getRace().getName() + ": " + this.getName() + "}";
  }

  public String getName() {
    return this.myName;
  }

  public void setName(String value) {
    this.myName = value;
  }

  public String getNickname() {
    return this.myNickname;
  }

  public void setNickname(String value) {
    this.myNickname = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  public void setRace(RaceEnum value) {
    this.myRace = value;
  }
}
