package net.dwarfguide.model.core;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public class CreatureRating extends MultiTuple._2<Creature, Integer> implements Comparable<CreatureRating> {
  public CreatureRating() {
    super();
  }

  public CreatureRating(Creature creature, Integer rating) {
    super(creature, rating);
  }

  public Creature creature(Creature value) {
    return super._0(value);
  }

  public Integer rating(Integer value) {
    return super._1(value);
  }

  public Creature creature() {
    return super._0();
  }

  public Integer rating() {
    return super._1();
  }

  @SuppressWarnings(value = "unchecked")
  public CreatureRating assignFrom(Tuples._2<Creature, Integer> from) {
    return (CreatureRating) super.assign(from);
  }

  public int compareTo(CreatureRating that) {
    return (int) that.rating() - (int) this.rating();
  }

  public String toString() {
    return this.creature() + ": " + (int) this.rating();
  }
}
