package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;
import java.util.List;

@Generated(value = {"MPS"}, date = "2011.10.14", comments = "Generated from model net.dwarfguide.modelnet.dwarfguide.model.core")
public interface CreatureLoader {
  public List<Creature> loadCreatures();
}
