package net.dwarfguide.model.core;

/*Generated by MPS */

import org.simpleframework.xml.Root;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Path;


/**
 * * @author Dmitry Sidorenko
 */
@Root(name = "Creature", strict = false)
public class CreatureXML {
  @Element
  private String name;
  @Element(required = false)
  private String nickname;
  @Element(required = false)
  private String customProfession = "";
  @Element
  private Sex sex;
  @Element
  private int age;
  @Element(name = "Profession")
  private ProfessionEnum profession;
  @Path(value = "Attributes")
  @Element(name = "Recuperation")
  private int Recuperation;
  @Path(value = "Attributes")
  @Element(name = "DiseaseResistance")
  private int DiseaseResistance;
  @Path(value = "Attributes")
  @Element(name = "Willpower")
  private int Willpower;
  @Path(value = "Attributes")
  @Element(name = "Memory")
  private int Memory;
  @Path(value = "Attributes")
  @Element(name = "Focus")
  private int Focus;
  @Path(value = "Attributes")
  @Element(name = "Intuition")
  private int Intuition;
  @Path(value = "Attributes")
  @Element(name = "Patience")
  private int Patience;
  @Path(value = "Attributes")
  @Element(name = "Empathy")
  private int Empathy;
  @Path(value = "Attributes")
  @Element(name = "SocialAwareness")
  private int SocialAwareness;
  @Path(value = "Attributes")
  @Element(name = "Creatvity")
  private int Creatvity;
  @Path(value = "Attributes")
  @Element(name = "Musicality")
  private int Musicality;
  @Path(value = "Attributes")
  @Element(name = "LinguisticAbility")
  private int LinguisticAbility;
  @Path(value = "Attributes")
  @Element(name = "SpatialSense")
  private int SpatialSense;
  @Path(value = "Attributes")
  @Element(name = "KinaestheticSense")
  private int KinaestheticSense;
  @Path(value = "Attributes")
  @Element(name = "AnalyticalAbility")
  private int AnalyticalAbility;
  @Path(value = "Attributes")
  @Element(name = "Strength")
  private int Strength;
  @Path(value = "Attributes")
  @Element(name = "Agility")
  private int Agility;
  @Path(value = "Attributes")
  @Element(name = "Toughness")
  private int Toughness;
  @Path(value = "Attributes")
  @Element(name = "Endurance")
  private int Endurance;

  public CreatureXML() {
  }

  public String getName() {
    return name;
  }

  public String getNickname() {
    return nickname;
  }

  public String getCustomProfession() {
    return customProfession;
  }

  public Sex getSex() {
    return sex;
  }

  public int getAge() {
    return age;
  }
}
