package net.dwarfguide.model.core;

/*Generated by MPS */

import java.util.Map;
import java.util.EnumMap;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class CreatureStatisticsManager {
  private Map<RaceEnum, CreatureStatistic> statistics;

  public CreatureStatisticsManager() {
    statistics = new EnumMap<RaceEnum, CreatureStatistic>(RaceEnum.class);


    Map<AttributeEnum, StatisticsTuple> ss;
    ss = MapSequence.fromMap(new HashMap<AttributeEnum, StatisticsTuple>());

    Map<AttributeEnum, StatisticsTuple> stats;
    CreatureStatistic creatureStatistic;

    // Statistics for dwarf 
    stats = new EnumMap<AttributeEnum, StatisticsTuple>(AttributeEnum.class);
    stats.put(AttributeEnum.STRENGTH, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.AGILITY, new StatisticsTuple(0, 5000, 900));
    stats.put(AttributeEnum.TOUGHNESS, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.ENDURANCE, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.DISEASERESISTANCE, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.RECUPERATION, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.ANALYTICALABILITY, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.MEMORY, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.CREATVITY, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.INTUITION, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.FOCUS, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.WILLPOWER, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.PATIENCE, new StatisticsTuple(0, 5000, 1250));
    stats.put(AttributeEnum.SPATIALSENSE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.KINAESTHETICSENSE, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.LINGUISTICABILITY, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.MUSICALITY, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.EMPATHY, new StatisticsTuple(0, 5000, 1000));
    stats.put(AttributeEnum.SOCIALAWARENESS, new StatisticsTuple(0, 5000, 1000));

    creatureStatistic = new CreatureStatistic(RaceEnum.DWARF, stats);
    statistics.put(RaceEnum.DWARF, creatureStatistic);

    // Statistics for goblin 
    stats = new EnumMap<AttributeEnum, StatisticsTuple>(AttributeEnum.class);
    stats.put(AttributeEnum.FOCUS, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.KINAESTHETICSENSE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.SPATIALSENSE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.LINGUISTICABILITY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.ANALYTICALABILITY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.MUSICALITY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.CREATVITY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.SOCIALAWARENESS, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.EMPATHY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.PATIENCE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.INTUITION, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.MEMORY, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.WILLPOWER, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.DISEASERESISTANCE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.RECUPERATION, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.TOUGHNESS, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.STRENGTH, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.ENDURANCE, new StatisticsTuple(0, 5000, 1500));
    stats.put(AttributeEnum.AGILITY, new StatisticsTuple(0, 5000, 1500));

    creatureStatistic = new CreatureStatistic(RaceEnum.GOBLIN, stats);
    statistics.put(RaceEnum.GOBLIN, creatureStatistic);

  }
}
