package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.16", comments = "Generated from model net.dwarfguide.model.core")
public class DwarfStats {
  public static RaceEnum race = RaceEnum.DWARF;
  public static final int MIN_FOCUS = 0;
  public static final int MIN_KINAESTHETICSENSE = 0;
  public static final int MIN_SPATIALSENSE = 0;
  public static final int MIN_LINGUISTICABILITY = 0;
  public static final int MIN_ANALYTICALABILITY = 0;
  public static final int MIN_MUSICALITY = 0;
  public static final int MIN_CREATVITY = 0;
  public static final int MIN_SOCIALAWARENESS = 0;
  public static final int MIN_EMPATHY = 0;
  public static final int MIN_PATIENCE = 0;
  public static final int MIN_INTUITION = 0;
  public static final int MIN_MEMORY = 0;
  public static final int MIN_WILLPOWER = 0;
  public static final int MIN_DISEASERESISTANCE = 0;
  public static final int MIN_RECUPERATION = 0;
  public static final int MIN_NIMBLNESS = 0;
  public static final int MIN_TOUGHNESS = 0;
  public static final int MIN_STRENGTH = 0;
  public static final int MIN_ENDURANCE = 0;
  public static final int MIN_AGILITY = 0;
  public static final int MAX_FOCUS = 5000;
  public static final int MAX_KINAESTHETICSENSE = 5000;
  public static final int MAX_SPATIALSENSE = 5000;
  public static final int MAX_LINGUISTICABILITY = 5000;
  public static final int MAX_ANALYTICALABILITY = 5000;
  public static final int MAX_MUSICALITY = 5000;
  public static final int MAX_CREATVITY = 5000;
  public static final int MAX_SOCIALAWARENESS = 5000;
  public static final int MAX_EMPATHY = 5000;
  public static final int MAX_PATIENCE = 5000;
  public static final int MAX_INTUITION = 5000;
  public static final int MAX_MEMORY = 5000;
  public static final int MAX_WILLPOWER = 5000;
  public static final int MAX_DISEASERESISTANCE = 5000;
  public static final int MAX_RECUPERATION = 5000;
  public static final int MAX_NIMBLNESS = 5000;
  public static final int MAX_TOUGHNESS = 5000;
  public static final int MAX_STRENGTH = 5000;
  public static final int MAX_ENDURANCE = 5000;
  public static final int MAX_AGILITY = 5000;
  public static final int AVG_FOCUS = 1500;
  public static final int AVG_KINAESTHETICSENSE = 1500;
  public static final int AVG_SPATIALSENSE = 1500;
  public static final int AVG_LINGUISTICABILITY = 1500;
  public static final int AVG_ANALYTICALABILITY = 1500;
  public static final int AVG_MUSICALITY = 1500;
  public static final int AVG_CREATVITY = 1500;
  public static final int AVG_SOCIALAWARENESS = 1500;
  public static final int AVG_EMPATHY = 1500;
  public static final int AVG_PATIENCE = 1500;
  public static final int AVG_INTUITION = 1500;
  public static final int AVG_MEMORY = 1500;
  public static final int AVG_WILLPOWER = 1500;
  public static final int AVG_DISEASERESISTANCE = 1500;
  public static final int AVG_RECUPERATION = 1500;
  public static final int AVG_NIMBLNESS = 1500;
  public static final int AVG_TOUGHNESS = 1500;
  public static final int AVG_STRENGTH = 1500;
  public static final int AVG_ENDURANCE = 1500;
  public static final int AVG_AGILITY = 1500;

  public DwarfStats() {
  }
}
