package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public class GoblinStats {
  public static RaceEnum race = RaceEnum.GOBLIN;
  public static final int MIN_NIMBLNESS = 0;
  public static final int MIN_TOUGHNESS = 0;
  public static final int MIN_STRENGTH = 0;
  public static final int MIN_ENDURANCE = 0;
  public static final int MIN_AGILITY = 0;
  public static final int MAX_NIMBLNESS = 5000;
  public static final int MAX_TOUGHNESS = 5000;
  public static final int MAX_STRENGTH = 5000;
  public static final int MAX_ENDURANCE = 5000;
  public static final int MAX_AGILITY = 5000;
  public static final int AVG_NIMBLNESS = 1500;
  public static final int AVG_TOUGHNESS = 1500;
  public static final int AVG_STRENGTH = 1500;
  public static final int AVG_ENDURANCE = 1500;
  public static final int AVG_AGILITY = 1500;

  public GoblinStats() {
  }
}
