package net.dwarfguide.model.core;

/*Generated by MPS */

import com.google.inject.AbstractModule;

public class MPSModule extends AbstractModule {
  private String xmlFile;

  public MPSModule(String xmlFile) {
    this.xmlFile = xmlFile;
  }

  protected void configure() {
    // Should use XMLFile annotation. After [MPS-14390] fixed. 
    bind(RatingStrategyFactory.class).to(RatingStrategyFactoryConcrete.class);
    bind(CreatureLoader.class).toInstance(new CreatureRunesmithLoader(xmlFile));
    bind(CreatureStatisticsManager.class).toInstance(new CreatureStatisticsManager());
  }
}
