package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingAnimal_DissectorGoblin extends AbstractRatingStrategy {
  public RatingAnimal_DissectorGoblin(CreatureStatisticsManager statisticsManager) {
    super("Strategy for goblin animal dissector", RaceEnum.GOBLIN, ProfessionEnum.ANIMAL_DISSECTOR, statisticsManager);
  }

  public int getRating(Creature creature) {
    return creature.getTrait(TraitEnum.ACTIVENESS) + 1 - (int) statisticsManager.getStats(creature.getRace(), AttributeEnum.CREATVITY).max();
  }
}
