package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public interface RatingStrategy {
  public int getRating(Creature creature);
  public boolean shouldStop(Creature creature);
}
