package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingMinerDwarf extends AbstractRatingStrategy {
  public RatingMinerDwarf() {
    super("Strategy for dwarven miner", RaceEnum.DWARF, ProfessionEnum.MINER);
  }

  public int getRating(Creature creature) {
    return creature.getTrait(TraitEnum.ADVENTURE) + 2 - DwarfStats.MAX_ENDURANCE;
  }
}
