package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingArmorerDwarf extends AbstractRatingStrategy {
  public RatingArmorerDwarf() {
    super("Strategy for dwarven armorer", RaceEnum.DWARF, ProfessionEnum.ARMORER);
  }

  public int getRating(Creature creature) {
    return creature.getTrait(TraitEnum.ADVENTURE) + 2 - DwarfStats.getMax(AttributeEnum.ENDURANCE);
  }
}
