package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingAlchemistDwarf implements RatingStrategy {
  private String myDescription;
  private RaceEnum myRace;
  private ProfessionEnum myProfession;

  public RatingAlchemistDwarf() {
    this.setDescription("Strategy for dwarven alchemist");
    this.setRace(RaceEnum.DWARF);
    this.setProfession(ProfessionEnum.ALCHEMIST);
  }

  public int getRating(Creature creature) {
    return creature.getSkill(SkillEnum.APPRAISAL);
  }

  public boolean shouldStop(Creature creature) {
    return false;
  }

  public String getDescription() {
    return this.myDescription;
  }

  private void setDescription(String value) {
    this.myDescription = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public ProfessionEnum getProfession() {
    return this.myProfession;
  }

  private void setProfession(ProfessionEnum value) {
    this.myProfession = value;
  }
}
