package net.dwarfguide.model.core;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class RatingStrategyFactory {
  private Map<RaceProfession, RatingStrategy> strategies;

  public RatingStrategyFactory() {
    strategies = MapSequence.fromMap(new HashMap<RaceProfession, RatingStrategy>());
  }

  public RatingStrategy getStrategy(RaceEnum raceEnum, ProfessionEnum professionEnum) {
    if (MapSequence.fromMap(strategies).containsKey(new RaceProfession(raceEnum, professionEnum))) {
      return MapSequence.fromMap(strategies).get(new RaceProfession(raceEnum, professionEnum));
    }
    // No strategy found, return NullObject 
    return new RatingStrategy() {
      public int getRating(Creature creature) {
        return 0;
      }

      public boolean shouldStop(Creature creature) {
        return false;
      }
    };
  }
}
