package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingStrategyFactory {
  public RatingStrategyFactory() {
  }

  public RatingStrategy getStrategy(RaceEnum raceEnum, ProfessionEnum professionEnum) {
    if (RaceEnum.DWARF.equals(raceEnum) && ProfessionEnum.WOODCRAFTER.equals(professionEnum)) {
      return new RatingWoodcrafterDwarf();
    }
    if (RaceEnum.GOBLIN.equals(raceEnum) && ProfessionEnum.ADMINISTRATOR.equals(professionEnum)) {
      return new RatingAdministratorGoblin();
    }
    if (RaceEnum.DWARF.equals(raceEnum) && ProfessionEnum.AXEMAN.equals(professionEnum)) {
      return new RatingAxemanDwarf();
    }
    // No strategy found, return NullObject 
    return new RatingStrategy() {
      public int getRating(Creature creature) {
        return 0;
      }

      public boolean shouldStop(Creature creature) {
        return false;
      }
    };
  }
}
