package net.dwarfguide.model.core;

/*Generated by MPS */


public class RatingAxemanDwarf implements RatingStrategy {
  private String myDescription;
  private RaceEnum myRace;
  private ProfessionEnum myProfession;

  public RatingAxemanDwarf() {
    this.setDescription("Strategy for dwarven axeman");
    this.setRace(RaceEnum.DWARF);
    this.setProfession(ProfessionEnum.AXEMAN);
  }

  public int getRating(Creature creature) {
    return creature.getAttribute(AttributeEnum.STRENGTH) - DwarfStats.AVG_STRENGTH;
  }

  public boolean shouldStop(Creature creature) {
    return creature.getTrait(TraitEnum.FRIENDLY) > 30;
  }

  public String getDescription() {
    return this.myDescription;
  }

  private void setDescription(String value) {
    this.myDescription = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public ProfessionEnum getProfession() {
    return this.myProfession;
  }

  private void setProfession(ProfessionEnum value) {
    this.myProfession = value;
  }
}
