package net.dwarfguide.model.core;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public class TraitInstance extends MultiTuple._3<TraitEnum, Integer, Integer> {
  public TraitInstance() {
    super();
  }

  public TraitInstance(TraitEnum trait, Integer level, Integer experience) {
    super(trait, level, experience);
  }

  public TraitEnum trait(TraitEnum value) {
    return super._0(value);
  }

  public Integer level(Integer value) {
    return super._1(value);
  }

  public Integer experience(Integer value) {
    return super._2(value);
  }

  public TraitEnum trait() {
    return super._0();
  }

  public Integer level() {
    return super._1();
  }

  public Integer experience() {
    return super._2();
  }

  @SuppressWarnings(value = "unchecked")
  public TraitInstance assignFrom(Tuples._3<TraitEnum, Integer, Integer> from) {
    return (TraitInstance) super.assign(from);
  }
}
