package net.dwarfguide.model.core;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.16", comments = "Generated from model net.dwarfguide.model.core")
public @interface XMLFile {
}
