package net.dwarfguide.model.core;

/*Generated by MPS */

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.annotation.ElementType;
import com.google.inject.BindingAnnotation;

@Retention(RetentionPolicy.RUNTIME)
@Target(value = {ElementType.PARAMETER})
@BindingAnnotation
public @interface XMLFile {
}
