package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */


public enum AttributeEnum {
  BODY("Body"),
  SOUL("Soul");

  private String name;

  AttributeEnum(String name) {
    this.name = name;
  }

  public String toString() {
    return name;
  }

  public String getName() {
    return name;
  }
}
