package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */


public class EnumRegistry<T extends Enum<T> & HasName> {
  private final <!TextGen not found for 'jetbrains.mps.baseLanguage.collections.structure.MapType'!> map = new <!TextGen not found for 'jetbrains.mps.baseLanguage.collections.structure.HashMapCreator'!>;
  private HasName workaround;

  public EnumRegistry() {
  }

  public void addEnum(T enumeration) {
    workaround = enumeration;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.collections.structure.MapElement'!> = enumeration;
  }

  public T findByName(String name) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.collections.structure.MapElement'!>;
  }
}
