package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */


public enum LabourEnum {
  MINING("Mining"),
  STONE_HAULING("Stone Hauling"),
  WOOD_HAULING("Wood Hauling"),
  BURIAL("Burial"),
  FOOD_HAULING("Food Hauling"),
  REFUSE_HAULING("Refuse Hauling"),
  ITEM_HAULING("Item Hauling"),
  FURNITURE_HAULING("Furniture Hauling"),
  ANIMAL_HAULING("Animal Hauling"),
  CLEANING("Cleaning"),
  WOOD_CUTTING("Wood Cutting"),
  CARPENTRY("Carpentry"),
  STONE_DETAILING("Stone Detailing"),
  MASONRY("Masonry"),
  ARCHITECTURE("Architecture"),
  ANIMAL_TRAINING("Animal Training"),
  ANIMAL_CARE("Animal Care"),
  DIAGNOSIS("Diagnosis"),
  SURGERY("Surgery"),
  SETTING_BONES("Setting Bones"),
  SUTURING("Suturing"),
  DRESSING_WOUNDS("Dressing Wounds"),
  FEED_PATIENTS_PRISONERS("Feed Patients/Prisoners"),
  RECOVERING_WOUNDED("Recovering Wounded"),
  BUTCHERY("Butchery"),
  TRAPPING("Trapping"),
  SMALL_ANIMAL_DISSECTION("Small Animal Dissection"),
  LEATHERWORKING("Leatherworking"),
  TANNING("Tanning"),
  BREWING("Brewing"),
  ALCHEMY("Alchemy"),
  SOAP_MAKER("Soap Maker"),
  WEAVING("Weaving"),
  CLOTHESMAKING("Clothesmaking"),
  MILLING("Milling"),
  PLANT_PROCESSING("Plant Processing"),
  CHEESE_MAKING("Cheese Making"),
  MILKING("Milking"),
  COOKING("Cooking"),
  FARMING_FIELDS_("Farming (Fields)"),
  PLANT_GATHERING("Plant Gathering"),
  FISHING("Fishing"),
  FISH_CLEANING("Fish Cleaning"),
  FISH_DISSECTION("Fish Dissection"),
  HUNTING("Hunting"),
  FURNACE_OPERATING("Furnace Operating"),
  WEAPONSMITHING("Weaponsmithing"),
  ARMORING("Armoring"),
  BLACKSMITHING("Blacksmithing"),
  METALCRAFTING("Metalcrafting"),
  GEM_CUTTING("Gem Cutting"),
  GEM_SETTING("Gem Setting"),
  WOODCRAFTING("Woodcrafting"),
  STONECRAFTING("Stonecrafting"),
  BONE_CARVING("Bone Carving"),
  GLASSMAKING("Glassmaking"),
  STRAND_EXTRACTION("Strand Extraction"),
  SIEGE_ENGINEERING("Siege Engineering"),
  SIEGE_OPERATING("Siege Operating"),
  CROSSBOW_MAKING("Crossbow-making"),
  MECHANICS("Mechanics"),
  POTASH_MAKING("Potash Making"),
  LYE_MAKING("Lye Making"),
  DYEING("Dyeing"),
  WOOD_BURNING("Wood Burning"),
  PUMP_OPERATING("Pump Operating"),
  SHEARING("Shearing"),
  SPINNING("Spinning"),
  POTTERY("Pottery"),
  GLAZING("Glazing"),
  PRESSING("Pressing"),
  BEE_KEEPING("Bee Keeping"),
  WAX_WORKING("Wax Working");

  private String name;

  LabourEnum(String name) {
    this.name = name;
  }

  public String toString() {
    return name;
  }
}
