package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */


public enum LevelEnum {
  DABBLING("Dabbling"),
  NOVICE("Novice"),
  ADEQUATE("Adequate"),
  COMPETENT("Competent"),
  SKILLED("Skilled"),
  PROFICIENT("Proficient"),
  TALENTED("Talented"),
  ADEPT("Adept"),
  EXPERT("Expert"),
  PROFESSIONAL("Professional"),
  ACCOMPLISHED("Accomplished"),
  GREAT("Great"),
  MASTER("Master"),
  HIGH_MASTER("High Master"),
  GRAND_MASTER("Grand Master"),
  LEGENDARY("Legendary"),
  LEGENDARY_1("Legendary+1"),
  LEGENDARY_2("Legendary+2"),
  LEGENDARY_3("Legendary+3"),
  LEGENDARY_4("Legendary+4"),
  LEGENDARY_5("Legendary+5");

  private String name;

  LevelEnum(String name) {
    this.name = name;
  }

  public String toString() {
    return name;
  }
}
