package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */


public enum MoodEnum {
  FEY("Fey"),
  SECRETIVE("Secretive"),
  POSSESED("Possesed"),
  MACABRE("Macabre"),
  FELL("Fell"),
  MELANCHOLY("Melancholy");

  private String name;

  MoodEnum(String name) {
    this.name = name;
  }

  public String toString() {
    return name;
  }
}
