package ru.sid0renk0.dwarfguide.game;

/*Generated by MPS */

import ru.sid0renk0.dwarfguide.model.configuration.Skill;

public class SkillsRepository {
  private Skill myMining;
  private Skill myWoodCutting;

  public SkillsRepository() {
    this.setMining(new Skill(0, "Mining"));
    this.setWoodCutting(new Skill(1, "Wood Cutting"));
  }

  public Skill getMining() {
    return this.myMining;
  }

  private void setMining(Skill value) {
    this.myMining = value;
  }

  public Skill getWoodCutting() {
    return this.myWoodCutting;
  }

  private void setWoodCutting(Skill value) {
    this.myWoodCutting = value;
  }
}
