package net.dwarfguide.creature.accessory;

/*Generated by MPS */

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import jetbrains.mps.generator.template.TemplateQueryContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;

public class GenerationUtils {
  public GenerationUtils() {
  }

  public static String when() {
    DateFormat format = new SimpleDateFormat("yyyy.MM.dd");
    return format.format(new Date());
  }

  public static String whenLong() {
    DateFormat format = DateFormat.getInstance();
    return format.format(new Date());
  }

  public static String who() {
    return "MPS";
  }

  public static String why(TemplateQueryContext gencontext) {
    return "Generated from model " + SModelOperations.getModelName(gencontext.getOriginalInputModel());
  }
}
