package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributesBasedStrategy extends BaseConcept implements RatingStrategy {
  public static final String concept = "net.dwarfguide.creature.structure.AttributesBasedStrategy";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String RACE_REF = "raceRef";
  public static final String PROFESSION_REF = "professionRef";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public AttributesBasedStrategy(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(AttributesBasedStrategy.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(AttributesBasedStrategy.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(AttributesBasedStrategy.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(AttributesBasedStrategy.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(AttributesBasedStrategy.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(AttributesBasedStrategy.VIRTUAL_PACKAGE, value);
  }

  public RaceRef getRaceRef() {
    return (RaceRef) this.getChild(RaceRef.class, AttributesBasedStrategy.RACE_REF);
  }

  public void setRaceRef(RaceRef node) {
    super.setChild(AttributesBasedStrategy.RACE_REF, node);
  }

  public ProfessionRef getProfessionRef() {
    return (ProfessionRef) this.getChild(ProfessionRef.class, AttributesBasedStrategy.PROFESSION_REF);
  }

  public void setProfessionRef(ProfessionRef node) {
    super.setChild(AttributesBasedStrategy.PROFESSION_REF, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(AttributesBasedStrategy.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, AttributesBasedStrategy.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, AttributesBasedStrategy.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(AttributesBasedStrategy.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, AttributesBasedStrategy.SMODEL_ATTRIBUTE, node);
  }

  public static AttributesBasedStrategy newInstance(SModel sm, boolean init) {
    return (AttributesBasedStrategy) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.AttributesBasedStrategy", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributesBasedStrategy newInstance(SModel sm) {
    return AttributesBasedStrategy.newInstance(sm, false);
  }
}
