package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributeStatistic extends BaseConcept {
  public static final String concept = "net.dwarfguide.creature.structure.AttributeStatistic";
  public static final String ATTR = "attr";
  public static final String AVERAGE = "average";
  public static final String MIN = "min";
  public static final String MAX = "max";

  public AttributeStatistic(SNode node) {
    super(node);
  }

  public AttributeRef getAttr() {
    return (AttributeRef) this.getChild(AttributeRef.class, AttributeStatistic.ATTR);
  }

  public void setAttr(AttributeRef node) {
    super.setChild(AttributeStatistic.ATTR, node);
  }

  public StatisticsField getAverage() {
    return (StatisticsField) this.getChild(StatisticsField.class, AttributeStatistic.AVERAGE);
  }

  public void setAverage(StatisticsField node) {
    super.setChild(AttributeStatistic.AVERAGE, node);
  }

  public StatisticsField getMin() {
    return (StatisticsField) this.getChild(StatisticsField.class, AttributeStatistic.MIN);
  }

  public void setMin(StatisticsField node) {
    super.setChild(AttributeStatistic.MIN, node);
  }

  public StatisticsField getMax() {
    return (StatisticsField) this.getChild(StatisticsField.class, AttributeStatistic.MAX);
  }

  public void setMax(StatisticsField node) {
    super.setChild(AttributeStatistic.MAX, node);
  }

  public static AttributeStatistic newInstance(SModel sm, boolean init) {
    return (AttributeStatistic) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.AttributeStatistic", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributeStatistic newInstance(SModel sm) {
    return AttributeStatistic.newInstance(sm, false);
  }
}
