package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributeRef extends Expression {
  public static final String concept = "net.dwarfguide.creature.structure.AttributeRef";
  public static final String ATTRIBUTE = "attribute";

  public AttributeRef(SNode node) {
    super(node);
  }

  public Attribute getAttribute() {
    return (Attribute) this.getReferent(Attribute.class, AttributeRef.ATTRIBUTE);
  }

  public void setAttribute(Attribute node) {
    super.setReferent(AttributeRef.ATTRIBUTE, node);
  }

  public static AttributeRef newInstance(SModel sm, boolean init) {
    return (AttributeRef) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.AttributeRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributeRef newInstance(SModel sm) {
    return AttributeRef.newInstance(sm, false);
  }
}
