package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Creature_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("ec18e679-bd6d-4441-a00b-ab06c2d44eec(net.dwarfguide.creature)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
