package net.dwarfguide.creature.structure;

/*Generated by MPS */


public interface Entity extends HasName, HasId {
  public static final String concept = "net.dwarfguide.creature.structure.Entity";
}
