package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface HasId extends INodeAdapter {
  public static final String concept = "net.dwarfguide.creature.structure.HasId";
  public static final String IDENTIFIER = "identifier";

  public int getIdentifier();
  public void setIdentifier(int value);
}
