package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface HasName extends INamedConcept {
  public static final String concept = "net.dwarfguide.creature.structure.HasName";
}
