package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface HasProfessionConstraint extends INodeAdapter {
  public static final String concept = "net.dwarfguide.creature.structure.HasProfessionConstraint";
  public static final String PROFESSION_REF = "professionRef";

  public ProfessionRef getProfessionRef();
  public void setProfessionRef(ProfessionRef node);
}
