package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface HasRaceContraint extends INodeAdapter {
  public static final String concept = "net.dwarfguide.creature.structure.HasRaceContraint";
  public static final String RACE_REF = "raceRef";

  public RaceRef getRaceRef();
  public void setRaceRef(RaceRef node);
}
