package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Labour extends BaseConcept implements Entity {
  public static final String concept = "net.dwarfguide.creature.structure.Labour";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String IDENTIFIER = "identifier";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Labour(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Labour.NAME);
  }

  public void setName(String value) {
    this.setProperty(Labour.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Labour.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Labour.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Labour.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Labour.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Labour.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Labour.VIRTUAL_PACKAGE, value);
  }

  public int getIdentifier() {
    return this.getIntegerProperty(Labour.IDENTIFIER);
  }

  public void setIdentifier(int value) {
    this.setIntegerProperty(Labour.IDENTIFIER, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Labour.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Labour.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Labour.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Labour.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Labour.SMODEL_ATTRIBUTE, node);
  }

  public static Labour newInstance(SModel sm, boolean init) {
    return (Labour) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.Labour", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Labour newInstance(SModel sm) {
    return Labour.newInstance(sm, false);
  }
}
