package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Level extends BaseConcept implements Entity {
  public static final String concept = "net.dwarfguide.creature.structure.Level";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String XP_NEXT_LEVEL = "xpNextLevel";
  public static final String IDENTIFIER = "identifier";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Level(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Level.NAME);
  }

  public void setName(String value) {
    this.setProperty(Level.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Level.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Level.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Level.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Level.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Level.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Level.VIRTUAL_PACKAGE, value);
  }

  public int getXpNextLevel() {
    return this.getIntegerProperty(Level.XP_NEXT_LEVEL);
  }

  public void setXpNextLevel(int value) {
    this.setIntegerProperty(Level.XP_NEXT_LEVEL, value);
  }

  public int getIdentifier() {
    return this.getIntegerProperty(Level.IDENTIFIER);
  }

  public void setIdentifier(int value) {
    this.setIntegerProperty(Level.IDENTIFIER, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Level.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Level.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Level.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Level.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Level.SMODEL_ATTRIBUTE, node);
  }

  public static Level newInstance(SModel sm, boolean init) {
    return (Level) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.Level", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Level newInstance(SModel sm) {
    return Level.newInstance(sm, false);
  }
}
