package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProfessionRef extends BaseConcept {
  public static final String concept = "net.dwarfguide.creature.structure.ProfessionRef";
  public static final String PROFESSION = "profession";

  public ProfessionRef(SNode node) {
    super(node);
  }

  public Profession getProfession() {
    return (Profession) this.getReferent(Profession.class, ProfessionRef.PROFESSION);
  }

  public void setProfession(Profession node) {
    super.setReferent(ProfessionRef.PROFESSION, node);
  }

  public static ProfessionRef newInstance(SModel sm, boolean init) {
    return (ProfessionRef) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.ProfessionRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProfessionRef newInstance(SModel sm) {
    return ProfessionRef.newInstance(sm, false);
  }
}
