package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Race extends BaseConcept implements Entity {
  public static final String concept = "net.dwarfguide.creature.structure.Race";
  public static final String SINGULAR = "singular";
  public static final String PLURAL = "plural";
  public static final String ADJECTIVE = "adjective";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String IDENTIFIER = "identifier";
  public static final String ATTRIBUTE_STATISTIC = "attributeStatistic";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Race(SNode node) {
    super(node);
  }

  public String getSingular() {
    return this.getProperty(Race.SINGULAR);
  }

  public void setSingular(String value) {
    this.setProperty(Race.SINGULAR, value);
  }

  public String getPlural() {
    return this.getProperty(Race.PLURAL);
  }

  public void setPlural(String value) {
    this.setProperty(Race.PLURAL, value);
  }

  public String getAdjective() {
    return this.getProperty(Race.ADJECTIVE);
  }

  public void setAdjective(String value) {
    this.setProperty(Race.ADJECTIVE, value);
  }

  public String getName() {
    return this.getProperty(Race.NAME);
  }

  public void setName(String value) {
    this.setProperty(Race.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Race.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Race.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Race.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Race.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Race.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Race.VIRTUAL_PACKAGE, value);
  }

  public int getIdentifier() {
    return this.getIntegerProperty(Race.IDENTIFIER);
  }

  public void setIdentifier(int value) {
    this.setIntegerProperty(Race.IDENTIFIER, value);
  }

  public int getAttributeStatisticsCount() {
    return this.getChildCount(Race.ATTRIBUTE_STATISTIC);
  }

  public Iterator<AttributeStatistic> attributeStatistics() {
    return this.children(AttributeStatistic.class, Race.ATTRIBUTE_STATISTIC);
  }

  public List<AttributeStatistic> getAttributeStatistics() {
    return this.getChildren(AttributeStatistic.class, Race.ATTRIBUTE_STATISTIC);
  }

  public void addAttributeStatistic(AttributeStatistic node) {
    this.addChild(Race.ATTRIBUTE_STATISTIC, node);
  }

  public void insertAttributeStatistic(AttributeStatistic prev, AttributeStatistic node) {
    this.insertChild(prev, Race.ATTRIBUTE_STATISTIC, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Race.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Race.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Race.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Race.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Race.SMODEL_ATTRIBUTE, node);
  }

  public static Race newInstance(SModel sm, boolean init) {
    return (Race) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.Race", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Race newInstance(SModel sm) {
    return Race.newInstance(sm, false);
  }
}
