package net.dwarfguide.creature.structure;

/*Generated by MPS */


public interface RatingStrategy extends HasRaceContraint, HasProfessionConstraint {
  public static final String concept = "net.dwarfguide.creature.structure.RatingStrategy";
}
