package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SkillRef extends Expression {
  public static final String concept = "net.dwarfguide.creature.structure.SkillRef";
  public static final String SKILL = "skill";

  public SkillRef(SNode node) {
    super(node);
  }

  public Skill getSkill() {
    return (Skill) this.getReferent(Skill.class, SkillRef.SKILL);
  }

  public void setSkill(Skill node) {
    super.setReferent(SkillRef.SKILL, node);
  }

  public static SkillRef newInstance(SModel sm, boolean init) {
    return (SkillRef) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.SkillRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SkillRef newInstance(SModel sm) {
    return SkillRef.newInstance(sm, false);
  }
}
