package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StatisticsField extends BaseConcept {
  public static final String concept = "net.dwarfguide.creature.structure.StatisticsField";
  public static final String STATISTIC = "statistic";

  public StatisticsField(SNode node) {
    super(node);
  }

  public int getStatistic() {
    return this.getIntegerProperty(StatisticsField.STATISTIC);
  }

  public void setStatistic(int value) {
    this.setIntegerProperty(StatisticsField.STATISTIC, value);
  }

  public static StatisticsField newInstance(SModel sm, boolean init) {
    return (StatisticsField) SModelUtil_new.instantiateConceptDeclaration("net.dwarfguide.creature.structure.StatisticsField", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StatisticsField newInstance(SModel sm) {
    return StatisticsField.newInstance(sm, false);
  }
}
