package net.dwarfguide.creature.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"net.dwarfguide.creature.structure.Attribute", "net.dwarfguide.creature.structure.AttributeRef", "net.dwarfguide.creature.structure.AttributeStatistic", "net.dwarfguide.creature.structure.AttributesBasedStrategy", "net.dwarfguide.creature.structure.Entity", "net.dwarfguide.creature.structure.Feature", "net.dwarfguide.creature.structure.FormulaRatingStrategy", "net.dwarfguide.creature.structure.HasId", "net.dwarfguide.creature.structure.HasName", "net.dwarfguide.creature.structure.HasProfessionConstraint", "net.dwarfguide.creature.structure.HasRaceContraint", "net.dwarfguide.creature.structure.Job", "net.dwarfguide.creature.structure.Labour", "net.dwarfguide.creature.structure.LabourCategory", "net.dwarfguide.creature.structure.LabourRef", "net.dwarfguide.creature.structure.Level", "net.dwarfguide.creature.structure.Profession", "net.dwarfguide.creature.structure.ProfessionRef", "net.dwarfguide.creature.structure.Race", "net.dwarfguide.creature.structure.RaceRef", "net.dwarfguide.creature.structure.RatingStrategy", "net.dwarfguide.creature.structure.Skill", "net.dwarfguide.creature.structure.SkillRef", "net.dwarfguide.creature.structure.Statistic", "net.dwarfguide.creature.structure.StatisticsField", "net.dwarfguide.creature.structure.Trait", "net.dwarfguide.creature.structure.TraitRef"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Attribute", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Feature", "net.dwarfguide.creature.structure.Entity"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.AttributeRef", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{}, new String[]{"attribute"});
      case 2:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.AttributeStatistic", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.AttributesBasedStrategy", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.RatingStrategy"}, new String[]{}, new String[]{});
      case 4:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Entity", null, true, new String[]{"net.dwarfguide.creature.structure.HasName", "net.dwarfguide.creature.structure.HasId"}, new String[]{}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Feature", null, true, new String[]{"net.dwarfguide.creature.structure.HasName"}, new String[]{}, new String[]{});
      case 6:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.FormulaRatingStrategy", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.RatingStrategy"}, new String[]{}, new String[]{});
      case 7:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.HasId", null, true, new String[]{}, new String[]{"identifier"}, new String[]{});
      case 8:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.HasName", null, true, new String[]{"jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{});
      case 9:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.HasProfessionConstraint", null, true, new String[]{}, new String[]{}, new String[]{});
      case 10:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.HasRaceContraint", null, true, new String[]{}, new String[]{}, new String[]{});
      case 11:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Job", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity"}, new String[]{}, new String[]{});
      case 12:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Labour", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity"}, new String[]{}, new String[]{});
      case 13:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.LabourCategory", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.HasName"}, new String[]{}, new String[]{});
      case 14:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.LabourRef", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{"labour"});
      case 15:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Level", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity"}, new String[]{"xpNextLevel"}, new String[]{});
      case 16:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Profession", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity"}, new String[]{"military", "canAssignLabors"}, new String[]{});
      case 17:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.ProfessionRef", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{"profession"});
      case 18:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Race", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity"}, new String[]{"singular", "plural", "adjective"}, new String[]{});
      case 19:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.RaceRef", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{"race"});
      case 20:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.RatingStrategy", null, true, new String[]{"net.dwarfguide.creature.structure.HasRaceContraint", "net.dwarfguide.creature.structure.HasProfessionConstraint"}, new String[]{}, new String[]{});
      case 21:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Skill", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity", "net.dwarfguide.creature.structure.Feature"}, new String[]{}, new String[]{});
      case 22:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.SkillRef", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{}, new String[]{"skill"});
      case 23:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Statistic", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{"statisticType"}, new String[]{});
      case 24:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.StatisticsField", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{"statistic"}, new String[]{});
      case 25:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.Trait", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "net.dwarfguide.creature.structure.Entity", "net.dwarfguide.creature.structure.Feature"}, new String[]{"highest", "veryHigh", "high", "low", "veryLow", "lowest"}, new String[]{});
      case 26:
        return new CompiledConceptDescriptor("net.dwarfguide.creature.structure.TraitRef", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{}, new String[]{"trait"});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
