package net.dwarfguide.framework.core;

/*Generated by MPS */

import javax.annotation.Generated;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.LinkedHashMap;

@Generated(value = {"MPS"})
public class EnumRegistry<T extends Enum<T> & HasName> {
  private final Map<String, T> map = MapSequence.fromMap(new LinkedHashMap<String, T>(16, (float) 0.75, false));

  public EnumRegistry() {
  }

  public void addEnum(T enumeration) {
    MapSequence.fromMap(map).put(enumeration.name(), enumeration);
  }

  public T findByName(String name) {
    return MapSequence.fromMap(map).get(name);
  }
}
