package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public enum AttributeEnum {
  NIMBLNESS("Nimblness"),
  STRENGTH("Strength"),
  AGILITY("Agility"),
  TOUGHNESS("Toughness"),
  ENDURANCE("Endurance");

  private String name;

  AttributeEnum(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
}
