package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public class Creature {
  private String myName;
  private String myEnglishName;
  private String myNickname;
  private RaceEnum myRace;
  private String myCustomProfession;
  private int myHappiness;
  private String myBirthday;
  private int myAge;

  public Creature() {
  }

  public String getName() {
    return this.myName;
  }

  private void setName(String value) {
    this.myName = value;
  }

  public String getEnglishName() {
    return this.myEnglishName;
  }

  private void setEnglishName(String value) {
    this.myEnglishName = value;
  }

  public String getNickname() {
    return this.myNickname;
  }

  private void setNickname(String value) {
    this.myNickname = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public String getCustomProfession() {
    return this.myCustomProfession;
  }

  private void setCustomProfession(String value) {
    this.myCustomProfession = value;
  }

  public int getHappiness() {
    return this.myHappiness;
  }

  private void setHappiness(int value) {
    this.myHappiness = value;
  }

  public String getBirthday() {
    return this.myBirthday;
  }

  private void setBirthday(String value) {
    this.myBirthday = value;
  }

  public int getAge() {
    return this.myAge;
  }

  private void setAge(int value) {
    this.myAge = value;
  }
}
