package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;
import java.util.List;

@Generated(value = {"MPS"})
public interface CreatureLoader {
  public List<Creature> loadCreatures();
}
