package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;
import java.util.List;

@Generated(value = {"MPS"}, date = "2011.10.14", comments = "Generated from model sandboxsandbox")
public interface CreatureLoader {
  public List<Creature> loadCreatures();
}
