package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.14", comments = "Generated from model sandboxsandbox")
public class Creatures {
  public Creatures() {
  }
}
