package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.14", comments = "Generated from model sandboxsandbox")
public class Creature {
  private String myName;
  private String myNickname;
  private RaceEnum myRace;
  private int myAttrNimblness;
  private int myAttrStrength;
  private int myAttrAgility;
  private int myAttrToughness;
  private int myAttrEndurance;
  private int mySkillMining;
  private int mySkillGem_cutting;
  private int myTraitNervousness;
  private int myTraitRage;

  public Creature() {
    this.setTraitNervousness(50);
    this.setTraitRage(50);
  }

  public String getName() {
    return this.myName;
  }

  private void setName(String value) {
    this.myName = value;
  }

  public String getNickname() {
    return this.myNickname;
  }

  private void setNickname(String value) {
    this.myNickname = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public int getAttrNimblness() {
    return this.myAttrNimblness;
  }

  private void setAttrNimblness(int value) {
    this.myAttrNimblness = value;
  }

  public int getAttrStrength() {
    return this.myAttrStrength;
  }

  private void setAttrStrength(int value) {
    this.myAttrStrength = value;
  }

  public int getAttrAgility() {
    return this.myAttrAgility;
  }

  private void setAttrAgility(int value) {
    this.myAttrAgility = value;
  }

  public int getAttrToughness() {
    return this.myAttrToughness;
  }

  private void setAttrToughness(int value) {
    this.myAttrToughness = value;
  }

  public int getAttrEndurance() {
    return this.myAttrEndurance;
  }

  private void setAttrEndurance(int value) {
    this.myAttrEndurance = value;
  }

  public int getSkillMining() {
    return this.mySkillMining;
  }

  private void setSkillMining(int value) {
    this.mySkillMining = value;
  }

  public int getSkillGem_cutting() {
    return this.mySkillGem_cutting;
  }

  private void setSkillGem_cutting(int value) {
    this.mySkillGem_cutting = value;
  }

  public int getTraitNervousness() {
    return this.myTraitNervousness;
  }

  private void setTraitNervousness(int value) {
    this.myTraitNervousness = value;
  }

  public int getTraitRage() {
    return this.myTraitRage;
  }

  private void setTraitRage(int value) {
    this.myTraitRage = value;
  }
}
