package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "12 Oct 2011 23:55:22 GMT")
public class Creatures {
  public Creatures() {
  }
}
