package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public class Creature {
  private String myName;
  private String myNickname;
  private RaceEnum myRace;
  private int myAttrnimblness;
  private int myAttrstrength;
  private int myAttragility;
  private int myAttrtoughness;
  private int myAttrendurance;
  private int mySkillmining;
  private int mySkillgem_cutting;
  private int myTraitnervousness;
  private int myTraitrage;

  public Creature() {
    this.setTraitnervousness(50);
    this.setTraitrage(50);
  }

  public String getName() {
    return this.myName;
  }

  private void setName(String value) {
    this.myName = value;
  }

  public String getNickname() {
    return this.myNickname;
  }

  private void setNickname(String value) {
    this.myNickname = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public int getAttrnimblness() {
    return this.myAttrnimblness;
  }

  private void setAttrnimblness(int value) {
    this.myAttrnimblness = value;
  }

  public int getAttrstrength() {
    return this.myAttrstrength;
  }

  private void setAttrstrength(int value) {
    this.myAttrstrength = value;
  }

  public int getAttragility() {
    return this.myAttragility;
  }

  private void setAttragility(int value) {
    this.myAttragility = value;
  }

  public int getAttrtoughness() {
    return this.myAttrtoughness;
  }

  private void setAttrtoughness(int value) {
    this.myAttrtoughness = value;
  }

  public int getAttrendurance() {
    return this.myAttrendurance;
  }

  private void setAttrendurance(int value) {
    this.myAttrendurance = value;
  }

  public int getSkillmining() {
    return this.mySkillmining;
  }

  private void setSkillmining(int value) {
    this.mySkillmining = value;
  }

  public int getSkillgem_cutting() {
    return this.mySkillgem_cutting;
  }

  private void setSkillgem_cutting(int value) {
    this.mySkillgem_cutting = value;
  }

  public int getTraitnervousness() {
    return this.myTraitnervousness;
  }

  private void setTraitnervousness(int value) {
    this.myTraitnervousness = value;
  }

  public int getTraitrage() {
    return this.myTraitrage;
  }

  private void setTraitrage(int value) {
    this.myTraitrage = value;
  }
}
