package sandbox.df2001;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class EnumRegistry<T extends Enum<T> & HasName> {
  private final Map<String, T> map = MapSequence.fromMap(new HashMap<String, T>());
  private HasName workaround;

  public EnumRegistry() {
  }

  public void addEnum(T enumeration) {
    workaround = enumeration;
    MapSequence.fromMap(map).put(workaround.getName(), enumeration);
  }

  public T findByName(String name) {
    return MapSequence.fromMap(map).get(name);
  }
}
