package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"})
public class GoblinCreature {
  public static final int MIN_NIMBLNESS = 0;
  public static final int MIN_TOUGHNESS = 0;
  public static final int MIN_STRENGTH = 0;
  public static final int MIN_ENDURANCE = 0;
  public static final int MIN_AGILITY = 0;
  public static final int MAX_NIMBLNESS = 5000;
  public static final int MAX_TOUGHNESS = 5000;
  public static final int MAX_STRENGTH = 5000;
  public static final int MAX_ENDURANCE = 5000;
  public static final int MAX_AGILITY = 5000;
  public static final int AVG_NIMBLNESS = 1500;
  public static final int AVG_TOUGHNESS = 1500;
  public static final int AVG_STRENGTH = 1500;
  public static final int AVG_ENDURANCE = 1500;
  public static final int AVG_AGILITY = 1500;

  private String myName;
  private String myNickname;
  private RaceEnum myRace;
  private int myNimblness;
  private int myToughness;
  private int myStrength;
  private int myEndurance;
  private int myAgility;
  private int myGem_cutting;
  private int myMining;
  private int myNervousness;
  private int myRage;

  public GoblinCreature() {
    this.setRace(RaceEnum.GOBLIN);
    this.getNimblness();
  }

  public String getName() {
    return this.myName;
  }

  private void setName(String value) {
    this.myName = value;
  }

  public String getNickname() {
    return this.myNickname;
  }

  private void setNickname(String value) {
    this.myNickname = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public int getNimblness() {
    return this.myNimblness;
  }

  private void setNimblness(int value) {
    this.myNimblness = value;
  }

  public int getToughness() {
    return this.myToughness;
  }

  private void setToughness(int value) {
    this.myToughness = value;
  }

  public int getStrength() {
    return this.myStrength;
  }

  private void setStrength(int value) {
    this.myStrength = value;
  }

  public int getEndurance() {
    return this.myEndurance;
  }

  private void setEndurance(int value) {
    this.myEndurance = value;
  }

  public int getAgility() {
    return this.myAgility;
  }

  private void setAgility(int value) {
    this.myAgility = value;
  }

  public int getGem_cutting() {
    return this.myGem_cutting;
  }

  private void setGem_cutting(int value) {
    this.myGem_cutting = value;
  }

  public int getMining() {
    return this.myMining;
  }

  private void setMining(int value) {
    this.myMining = value;
  }

  public int getNervousness() {
    return this.myNervousness;
  }

  private void setNervousness(int value) {
    this.myNervousness = value;
  }

  public int getRage() {
    return this.myRage;
  }

  private void setRage(int value) {
    this.myRage = value;
  }
}
