package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.14", comments = "Generated from model sandboxsandbox")
public enum ProfessionEnum {
  WORKER("Worker"),
  IDIOT("Idiot"),
  GEM_CUTTER("Gem Cutter");

  private String name;

  ProfessionEnum(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
}
