package sandbox.df2001;

/*Generated by MPS */


public enum ProfessionEnum {
  WORKER("Worker"),
  IDIOT("Idiot"),
  GEM_CUTTER("Gem Cutter");

  private String name;

  ProfessionEnum(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
}
