package sandbox.df2001;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public class RaceProfession extends MultiTuple._2<RaceEnum, ProfessionEnum> {
  public RaceProfession() {
    super();
  }

  public RaceProfession(RaceEnum race, ProfessionEnum profession) {
    super(race, profession);
  }

  public RaceEnum race(RaceEnum value) {
    return super._0(value);
  }

  public ProfessionEnum profession(ProfessionEnum value) {
    return super._1(value);
  }

  public RaceEnum race() {
    return super._0();
  }

  public ProfessionEnum profession() {
    return super._1();
  }

  @SuppressWarnings(value = "unchecked")
  public RaceProfession assignFrom(Tuples._2<RaceEnum, ProfessionEnum> from) {
    return (RaceProfession) super.assign(from);
  }
}
