package sandbox.df2001;

/*Generated by MPS */


public class RatingStrategyFactory {
  public RatingStrategyFactory() {
  }

  public RatingStrategy getStrategy(RaceEnum raceEnum, ProfessionEnum professionEnum) {
    if (RaceEnum.DWARF.equals(raceEnum) && ProfessionEnum.GEM_CUTTER.equals(professionEnum)) {
      return new RatingGem_CutterDwarf();
    }
    // No strategy found, return NullObject 
    return new RatingStrategy() {
      public int getRating(Creature creature) {
        return 0;
      }

      public boolean shouldStop(Creature creature) {
        return false;
      }
    };
  }
}
