package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = {"MPS"}, date = "2011.10.16", comments = "Generated from model sandbox.df2001")
public interface RatingStrategy {
  public int getRating(Creature creature);
  public boolean shouldStop(Creature creature);
}
