package sandbox.df2001;

/*Generated by MPS */


public class StrategyClass {
  private DwarfCreature creature;

  public StrategyClass(DwarfCreature creature) {
    this.creature = creature;
  }

  public int getRating() {
    return 222;
  }

  public boolean shouldStop() {
    return 33 > 333;
  }
}
