/*
 * Copyright (c) 2010-2011, Dmitry Sidorenko. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sandbox.df2001;

/*Generated by MPS */


public class StrategyGem_cutterDwarf {
  private Creature creature;
  private String myDescription;
  private RaceEnum myRace;
  private ProfessionEnum myProfession;

  public StrategyGem_cutterDwarf(Creature creature) {
    this.creature = creature;
    this.setDescription("Strategy for dwarven gem cutter");
    this.setRace(RaceEnum.DWARF);
    this.setProfession(ProfessionEnum.GEM_CUTTER);
  }

  public int getRating() {
    return Math.abs((creature.getAgility() - DwarfStats.AVG_AGILITY));
  }

  public boolean shouldStop() {
    return false;
  }

  public String getDescription() {
    return this.myDescription;
  }

  private void setDescription(String value) {
    this.myDescription = value;
  }

  public RaceEnum getRace() {
    return this.myRace;
  }

  private void setRace(RaceEnum value) {
    this.myRace = value;
  }

  public ProfessionEnum getProfession() {
    return this.myProfession;
  }

  private void setProfession(ProfessionEnum value) {
    this.myProfession = value;
  }
}
