package sandbox.df2001;

/*Generated by MPS */

import javax.annotation.Generated;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

@Generated(value = {"MPS"})
public class TraitDecoder {
  private static final Map<String, TraitInstance> levels;

  public TraitDecoder() {
  }

  public TraitInstance findByName(String description) {
    return MapSequence.fromMap(levels).get(description);
  }

  static {
    levels = MapSequence.fromMap(new HashMap<String, TraitInstance>(400));

    MapSequence.fromMap(levels).put("Is a nervous wreck", new TraitInstance(TraitEnum.NERVOUSNESS, 0, 95));
    MapSequence.fromMap(levels).put("Is always tense and jittery", new TraitInstance(TraitEnum.NERVOUSNESS, 1, 83));
    MapSequence.fromMap(levels).put("Is often nervous", new TraitInstance(TraitEnum.NERVOUSNESS, 2, 68));
    MapSequence.fromMap(levels).put("Has a calm demeanor", new TraitInstance(TraitEnum.NERVOUSNESS, 3, 32));
    MapSequence.fromMap(levels).put("Has a very calm demeanor", new TraitInstance(TraitEnum.NERVOUSNESS, 4, 17));
    MapSequence.fromMap(levels).put("Has an incredibly calm demeanor", new TraitInstance(TraitEnum.NERVOUSNESS, 5, 5));
    MapSequence.fromMap(levels).put("high", new TraitInstance(TraitEnum.RAGE, 0, 95));
    MapSequence.fromMap(levels).put("2", new TraitInstance(TraitEnum.RAGE, 1, 83));
    MapSequence.fromMap(levels).put("3", new TraitInstance(TraitEnum.RAGE, 2, 68));
    MapSequence.fromMap(levels).put("4", new TraitInstance(TraitEnum.RAGE, 3, 32));
    MapSequence.fromMap(levels).put("5", new TraitInstance(TraitEnum.RAGE, 4, 17));
    MapSequence.fromMap(levels).put("6", new TraitInstance(TraitEnum.RAGE, 5, 5));

  }
}
