package sandbox.df2001;

/*Generated by MPS */


public enum TraitEnum {
  NERVOUSNESS("Nervousness"),
  RAGE("Rage");

  private String name;

  TraitEnum(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
}
